Set focus for term form
LuteOrg/lute-v3 pull request #390
Opened 2024-04-03 14:24 UTC by Jayanth-Parthsarathy

# Set focus properly for term form

## Fixes #379 

- [x] Add proper form focus for when creating new term, editing existing term, clicking on term in read page, etc.,

2024-04-05 03:40 UTC, jzohrab requested changes
Hi @Jayanth-Parthsarathy , can you make a few changes?

* the code should be moved inside the `$(document).ready(function () {` function block
* for uniformity, please use jquery-style `$("#someId")` instead of `document.getElementById()`
* please use spaces for indenting :-P

2024-04-05 04:33 UTC, Jayanth-Parthsarathy commented
@jzohrab  Made the changes as you have requested. My bad for not looking at the indentations.

2024-04-05 04:43 UTC, jzohrab commented
Thanks @Jayanth-Parthsarathy, I'll try it out, looks good!

2024-04-05 04:50 UTC, jzohrab commented
Works great, thanks!

2024-04-05 04:50 UTC, merged

2024-04-23 01:42 UTC, jzohrab commented
Well @Jayanth-Parthsarathy -- after all your work, I'm going to disable this change, sorry about that!

Prior to this change, I could use the left and right arrow keys to move from term to term in the reading pane, and the form would update, which is nice for easily moving through terms and updating things.  With this change, the form pulls focus, so the arrow keys stop working.

Sorry again, this is one of those things where I only get a feel of the features through my own usage.  Cheers!